name: Docker Build and Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Cypress config JSON
        run: echo ${{ secrets.OCR_KEY_JSON }} | base64 -d > ocr_key.json

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: wjdguswn1203/external:latest

      - name: check pwd
        run: pwd

      - name: Verify JSON format
        run: cat ocr_key.json | jq .
